### ISSUE TITLE
How can i get current time while i'm recording?

### ISSUE THREAD

**Issue by huurray** [react-native-audio-toolkit/react-native-audio-toolkit#216]
hello. i found there is current time for player.
but i couldn't find current time for recorder.
is there any way to get current time when i record??

thanks for reading this.

**Comment by sgerendasy** [comment]
I did something like this:

    this._recordStartTime = Date.now();
            this.recorder.record((e) => {
                this._recordingMSInterval = setInterval(() => {
                    this.setState({recordingDuration: Date.now() - this._recordStartTime});
            }, 50);
        });
