### ISSUE TITLE
I can't play recorded file on android

### ISSUE THREAD

**Issue by beqramo** [react-native-audio-toolkit/react-native-audio-toolkit#253]
I think the problem is in recording, I can play from URL. also I have problem uploading file on android because I think it isn't saving the file. I checked the file if it existed and it wasn't on my phone.

<img width="1422" alt="Screenshot 2021-02-02 at 10 44 09" src="https://user-images.githubusercontent.com/40486471/106562492-cf4bd600-6543-11eb-9d6a-9343c1b8e0dd.png">

```js

 recorderInstance.current = new Recorder('ssf.aac', { format: 'aac', quality: 'max' })
      .prepare()
      .record()


setTimeout(() =>{

    recorderInstance.current.stop(err => {
      new Player(recorderInstance.current.fsPath).play()

    })
},3000)

```

**Comment by beqramo** [comment]
closing, the solution is to use another library: https://github.com/dooboolab/react-native-audio-recorder-player

**Comment by hsavit1** [comment]
were you able to get the other lib to work?

**Comment by beqramo** [comment]
Yes, using the library above
