### ISSUE TITLE
debug mode work perfectly but the release mode not playing audio.

### ISSUE THREAD

**Issue by sabeelmuttil** [react-native-audio-toolkit/react-native-audio-toolkit#254]
debug mode work perfectly but the release mode not playing audio.

`` 

    let isAndroid = Platform.OS === 'android';
   this.player = new Player(this.props.audio, {
      autoDestroy: false,
      continuesToPlayInBarkground: false,
    });

    if (isAndroid) {
      this.player.speed = 0.0;
    }

    this.player.prepare(err => {
      console.log('prepared');
      if (err) {
        console.log('error at _reloadPlayer():');
        console.log(err);
      } else {
        this.player.playPause((err, paused) => {
          console.log('error', err);
          if (err) {
            this.setState({
              error: err.message,
            });
          } else {
            if (isAndroid && this.player) {
              this.player.speed = 1.0; // resetting to def.,
            }
          }
          this._updateState();
        });
        this.player.looping = this.state.loopButtonStatus;
      }

    });
``
this is my code

**Comment by nasir03082409229** [comment]
@sabeelmuttil how you fixed this issue?

**Comment by sabeelmuttil** [comment]
> @sabeelmuttil how you fixed this issue?

I think this supports only https urls in release mode. please check this one.

**Comment by sabeelmuttil** [comment]
> > @sabeelmuttil how you fixed this issue?
> 
> @nasir03082409229 I think this supports only https urls in release mode. please check this one.

exactly. only support https urls in release mode.

**Comment by mrigo** [comment]
I've the same error and the url is https....
I've playerId 2 not found ....
